In [6]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [7]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [8]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [9]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

TRAIN TEST SPLIT

In [10]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

SCALING KARNEGE ,KYUKI NN ME SAME SCALES KE DATA BHEJO

In [11]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [12]:
X_train

array([[-0.43994208, -0.28182512, -0.5052301 , ..., -1.47215862,
        -1.10178678, -1.67797825],
       [-0.05794787, -0.54493292, -0.02229308, ...,  0.80974336,
         1.28245153,  1.33168018],
       [ 1.55684581, -0.10872789,  1.53197736, ...,  1.43131479,
         0.66121836,  0.39298024],
       ...,
       [-1.26672801,  0.01128619, -1.27399552, ..., -1.13366246,
        -0.55735441, -0.25360055],
       [ 0.56713355,  0.91139182,  0.46901373, ..., -0.19533457,
         0.11849267,  0.06226812],
       [ 0.23144168, -0.54262496,  0.14217334, ..., -0.50213977,
        -0.60343489, -0.90255629]])

In [13]:
y_train

360    B
215    M
487    M
145    B
281    B
      ..
523    B
185    B
548    B
10     M
434    B
Name: diagnosis, Length: 455, dtype: object

In [23]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [24]:
y_test

array([1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1])

In [25]:
#now we are converting our numpy arrays into pytorch tensors
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

Defining The Model

In [26]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

IMPORTANT PARAMETERS

In [31]:
learning_rate=0.1
epochs=25

TRAINING PIPERLINE

In [32]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.424822737968574
Epoch: 2, Loss: 3.2927582036320926
Epoch: 3, Loss: 3.151779989293362
Epoch: 4, Loss: 3.009451481032872
Epoch: 5, Loss: 2.8616395834847204
Epoch: 6, Loss: 2.7095968594304156
Epoch: 7, Loss: 2.5492801819974815
Epoch: 8, Loss: 2.3832167664465556
Epoch: 9, Loss: 2.213430017205756
Epoch: 10, Loss: 2.043307031175777
Epoch: 11, Loss: 1.8738203896902792
Epoch: 12, Loss: 1.7100766204273448
Epoch: 13, Loss: 1.5564372536993525
Epoch: 14, Loss: 1.4147219036925516
Epoch: 15, Loss: 1.2790835529202549
Epoch: 16, Loss: 1.1569489777193782
Epoch: 17, Loss: 1.0544417380573465
Epoch: 18, Loss: 0.9717420373146594
Epoch: 19, Loss: 0.9075828959763658
Epoch: 20, Loss: 0.8595238492867723
Epoch: 21, Loss: 0.8244492145625838
Epoch: 22, Loss: 0.7991338918754941
Epoch: 23, Loss: 0.7807232238955886
Epoch: 24, Loss: 0.7669877297756235
Epoch: 25, Loss: 0.7563450678891595

EVALUATION

In [33]:
with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
print(y_pred)

tensor([[0.6730],
        [0.3877],
        [0.5705],
        [0.6092],
        [0.6033],
        [0.7080],
        [0.3805],
        [0.0685],
        [0.1413],
        [0.3183],
        [0.5464],
        [0.6530],
        [0.6169],
        [0.2937],
        [0.3104],
        [0.5555],
        [0.3172],
        [0.3965],
        [0.5862],
        [0.3054],
        [0.3241],
        [0.1261],
        [0.3031],
        [0.8097],
        [0.6218],
        [0.5749],
        [0.6625],
        [0.3359],
        [0.7786],
        [0.3546],
        [0.2482],
        [0.4924],
        [0.5170],
        [0.5443],
        [0.4355],
        [0.5258],
        [0.3970],
        [0.8752],
        [0.4298],
        [0.5585],
        [0.6807],
        [0.4560],
        [0.7353],
        [0.6344],
        [0.5482],
        [0.0573],
        [0.5809],
        [0.3536],
        [0.4248],
        [0.5579],
        [0.2206],
        [0.5275],
        [0.4511],
        [0.4033],
        [0.4485],
        [0.3616],
        [0.5603],
        [0.7423],
        [0.4128],
        [0.4429],
        [0.2387],
        [0.3867],
        [0.3082],
        [0.3307],
        [0.7661],
        [0.3845],
        [0.8447],
        [0.3749],
        [0.3959],
        [0.9084],
        [0.2849],
        [0.3388],
        [0.6376],
        [0.3942],
        [0.5264],
        [0.2745],
        [0.3836],
        [0.4032],
        [0.3133],
        [0.6051],
        [0.5571],
        [0.4973],
        [0.7644],
        [0.5054],
        [0.6625],
        [0.1948],
        [0.6983],
        [0.4891],
        [0.8590],
        [0.6141],
        [0.3450],
        [0.7022],
        [0.3797],
        [0.3833],
        [0.6328],
        [0.3676],
        [0.4413],
        [0.4117],
        [0.3161],
        [0.3816],
        [0.5727],
        [0.6582],
        [0.4877],
        [0.4186],
        [0.5576],
        [0.4943],
        [0.3319],
        [0.2947],
        [0.3531],
        [0.3461],
        [0.5985],
        [0.6914],
        [0.1221],
        [0.6875]], dtype=torch.float64)

In [34]:
#now we have to make prediction by comparing y_pred with y_test (in zero/one format)
# so will decide a threshould less than 0.5=0 and more than 0.5=1
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6034164428710938